Resources:
  FeedsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: owner
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: owner
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.FEEDS_TABLE}
      LocalSecondaryIndexes:
        - IndexName: ${self:provider.environment.FEEDS_ID_INDEX}
          KeySchema:
          - AttributeName: owner
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
          Projection:
            ProjectionType: ALL